# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background_Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('date_expiring', models.DateField()),
                ('granting_agency', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='license',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider_contact',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='background_check',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Driver'),
        ),
    ]
