# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20171001_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='company',
            new_name='provider',
        ),
    ]
