# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20171004_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.FileField(upload_to='provider_contracts')),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='contract_start_date',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='date_added',
        ),
        migrations.AddField(
            model_name='contract',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Provider'),
        ),
    ]
